apiVersion: v1
kind: Service
metadata:
  name: "team8-portal"
#修改到对应team的namespace
  namespace: team8
spec:
  type: NodePort
  ports:
#定义端口
  - name: http
  #Service暴露出的端口
    port: 20080
    #容器内端口，没有的话会直接指向port里写的
    targetPort: 9080
#指向应用名称selector
  selector:
    app: "team8-portal"